server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"   
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: M1
          uri: lb://M1
          predicates:
            - Path=/api/tools/**

        - id: M2
          uri: lb://M2
          predicates:
            - Path=/api/loans/**

        - id: M3
          uri: lb://M3
          predicates:
            - Path=/api/users/**

        - id: M4
          uri: lb://M4
          predicates:
            - Path=/api/rates/**

        - id: M5
          uri: lb://M5
          predicates:
            - Path=/api/kardex/**

        - id: M6
          uri: lb://M6
          predicates:
            - Path=/api/reports/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/