spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/ms1_db?allowPublicKeyRetrieval=true&useSSL=false
    username: ADMIN
    password: cris123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
server:
  port: ${PORT:0}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    ip-address: ${POD_IP:127.0.0.1}